<a href="https://colab.research.google.com/github/jreevesy/Linear-Algebra-58019/blob/main/Application.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**The price of one apple and one orange**##


In [5]:
import numpy as np

In [6]:
A = np.array([[20,10],[17,22]])
B = np.array([[350],[500]])
print(A)
print(B)

[[20 10]
 [17 22]]
[[350]
 [500]]


In [11]:
#other step on how to solve linear equations with NumPy and linalg.solve

A = np.array([[20,10],[17,22]])
B = np.array([[350],[500]])
print(A)
print(B)
X = np.linalg.solve(A,B)
print(X)

[[20 10]
 [17 22]]
[[350]
 [500]]
[[10.]
 [15.]]


In [14]:
import numpy as np
from scipy.linalg import solve #other option you can try using SciPy 

A = np.array([[20,10],[17,22]])
B = np.array([[350],[500]])
print(A)
print(B)
X = solve (A,B)
print(X)

[[20 10]
 [17 22]]
[[350]
 [500]]
[[10.]
 [15.]]


In [7]:
inv_A = np.linalg.inv(A) #Inverse of A
print(inv_A)
X = np.linalg.inv(A).dot(B) #unknown values of determining the x and y
print(X)

[[ 0.08148148 -0.03703704]
 [-0.06296296  0.07407407]]
[[10.]
 [15.]]


In [10]:
#other option that you can try

X = np.dot(inv_A,B)
print(X)

[[10.]
 [15.]]


##**Solving for three linear equations with unknown variables of x, y, and z**##

In [19]:
#4x+3y+2z=25
#-2z+2y+3z=-10
#3x-5y+2x=-4

A = np.array([[4,3,2],[-2,2,3],[3,-5,2]])
print(A)
B = np.array([[25],[-10],[-4]])
print (B)
X = solve(A,B) 
print(X)

[[ 4  3  2]
 [-2  2  3]
 [ 3 -5  2]]
[[ 25]
 [-10]
 [ -4]]
[[ 5.]
 [ 3.]
 [-2.]]
