<a href="https://colab.research.google.com/github/jreevesy/Linear-Algebra-58019/blob/main/FINAL_EXAM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **FINAL EXAM**

In [6]:
#problem one

import numpy as np

eq1 = np.array ([[1,1,1],[1,0,4],[0,0,5]])
eq2 = np.array ([[89],[89],[95]])
amt = np.linalg.inv(eq1).dot(eq2)
print (amt)

[[13.]
 [57.]
 [19.]]


In [8]:
#problem two

import numpy as np

A = np.array([[3,-1,1],[9,-3,3],[-12,4,-4]])
print(A)
B = np.array([[5],[15],[-20]])
print (B)

# compute the pseudo inverse of A
# computationally intensive for large problems
Apinv = np.linalg.pinv(A)

# apply the pseudo-inverse to the rhs
# vector to obtain the `solution'
x = Apinv.dot(B)
print(x)

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]
[[  5]
 [ 15]
 [-20]]
[[ 1.36363636]
 [-0.45454545]
 [ 0.45454545]]


In [5]:
#problem three

import numpy as np
from numpy.linalg import eig

A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print(A,"\n")
w,v = np.linalg.eig(A) 
print("The eigenvalues is/are:\n",w.round(),"\n") #print eigenvalues
print("The eigenvectors is/are:\n",v.round()) #print eigenvectors

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]] 

The eigenvalues is/are:
 [-1.  3.  2.] 

The eigenvectors is/are:
 [[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
