<a href="https://colab.research.google.com/github/jreevesy/Linear-Algebra-58019/blob/main/Linear_Transformation_Demo_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TO FIND THE INVERSE OF MATRIX, THE MATRIX IS PASSED TO THE linalg.inv() OF THE NUMPY MODULE**


In [1]:
import numpy as np
A = np.array ([[4,3],[-5,9]]) #creation of matrix A
print (A) #to display or print

[[ 4  3]
 [-5  9]]


In [3]:
import numpy as np
A = np.array ([[4,3],[-5,9]]) #creation of matrix A
print (A)
inv_A = np.linalg.inv(A) #to declare and creation of Inverse of A
print (inv_A) #to display or print

[[ 4  3]
 [-5  9]]
[[ 0.17647059 -0.05882353]
 [ 0.09803922  0.07843137]]


In [8]:
B = np.array ([[20],[26]]) #creation of Matrix B
print (B)

[[20]
 [26]]


In [6]:
X = np.linalg.inv(A).dot(B) #compute for the dot product of Inv of A & value of B
print (X)

[[2.]
 [4.]]


In [9]:
X = np.dot(inv_A,B) #to compute for the dot product of Inv of A and B
print (X)

[[2.]
 [4.]]


**YOU TRY!**

In [14]:
X = np.array([[4,3,2],[-2,2,3],[3,-5,2]]) #creation of Matrix X
y = np.array([[25],[-10],[-4]]) #creation of Matix y

inv_X = np.linalg.inv(X) #to Inverse the Matrix X
b = np.linalg.inv(X).dot(y) #To get dot product of Inverse of X and y

#to print or display
print(X)
print()
print(inv_X)
print()
print(y)
print()
print(b)


[[ 4  3  2]
 [-2  2  3]
 [ 3 -5  2]]

[[ 0.15447154 -0.1300813   0.04065041]
 [ 0.10569106  0.01626016 -0.1300813 ]
 [ 0.03252033  0.23577236  0.11382114]]

[[ 25]
 [-10]
 [ -4]]

[[ 5.]
 [ 3.]
 [-2.]]


In [10]:
A = np.array ([[20,10],[17,22]]) #creation of Matrix A
print (A)
inv_A = np.linalg.inv(A) #Inverse of matrix A
print (inv_A)

[[20 10]
 [17 22]]
[[ 0.08148148 -0.03703704]
 [-0.06296296  0.07407407]]


In [11]:
B= np.array([[350],[500]]) #Creation of Matrix B
print(B)

[[350]
 [500]]


In [12]:
X = np.dot(inv_A,B) #To get dot product of Inverse of A and B

print(X)

[[10.]
 [15.]]


In [13]:
B = np.dot(A,X)
print(B)

[[350.]
 [500.]]
