<a href="https://colab.research.google.com/github/jreevesy/Linear-Algebra-58019/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**QUESTION #1**


In [11]:
import numpy as np

square_matrix = np.identity(5)

print(f'Square Matrix whose length is 5: \n{square_matrix}')


Square Matrix whose length is 5: 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


**QUESTION #2**


In [14]:
import numpy as np

Q = np.array([[1,2,3,4,5],[0,6,7,8,9],[0,0,10,11,12],[0,0,0,13,14],[0,0,0,0,15]])
print(Q)

[[ 1  2  3  4  5]
 [ 0  6  7  8  9]
 [ 0  0 10 11 12]
 [ 0  0  0 13 14]
 [ 0  0  0  0 15]]


**QUESTION #3**

In [17]:
import numpy as np

square_matrix = np.array ([[6,7,8,9,10],
                           [7,6,7,8,9],
                           [8,7,6,7,8],
                           [9,8,7,6,7],
                           [10,9,8,7,6]])
#prints a square matrix which is symmetrical

print('A square matrix which is symmetrical')
print(square_matrix)

A square matrix which is symmetrical
[[ 6  7  8  9 10]
 [ 7  6  7  8  9]
 [ 8  7  6  7  8]
 [ 9  8  7  6  7]
 [10  9  8  7  6]]


**QUESTION #4**

In [4]:
import numpy as np

C = np.array ([[1,2,3],[2,3,3],[3,4,-2]])

invC = np.linalg.inv(C) #Inverse of Matrix C

print(invC)

[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


**QUESTION #5**

In [6]:
import numpy as np

C = np.array ([[1,2,3],[2,3,3],[3,4,-2]])

detOfC = np.linalg.det(C)

print("Determinant of the given matrix in Question 4:")
print(int(detOfC))

Determinant of the given matrix in Question 4:
5


**QUESTION #6**

In [7]:
import numpy as np 

Equations = np.array([[5,4,1],
                      [10,9,4],
                      [10,13,15]])

Constants = np.array([[[3.4],
                       [8.8],
                       [19.2]]])

roots = np.linalg.inv(Equations) @ Constants

print(roots)

[[[0.2]
  [0.4]
  [0.8]]]
