<a href="https://colab.research.google.com/github/jreevesy/Linear-Algebra-58019/blob/main/PRELIM_EXAM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Question #1**


In [1]:
import numpy as np

C = np.eye(4)
print(C)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Question #2**

In [5]:
answer = 2*C

print(answer)

[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


**Question #3**


In [4]:
A = np.array([2,7,4])
B = np.array([3,9,8])
cross = np.cross(A,B)
print(cross)

[20 -4 -3]
