<a href="https://colab.research.google.com/github/jreevesy/Linear-Algebra-58019/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix and Its Operations


In [4]:
import numpy as np
a = np.array ([[-5,0],[4,1]])
b = np.array ([[6,-3],[2,3]])

sum = np.add (a,b)

print ("Sum of a and b")
print (sum)

Sum of a and b
[[ 1 -3]
 [ 6  4]]


In [5]:
import numpy as np
a = np.array ([[-5,0],[4,1]])
b = np.array ([[6,-3],[2,3]])

difference1 = np.subtract (a,b)

print ("\nDifference of a and b")
print (difference1)


Difference of a and b
[[-11   3]
 [  2  -2]]


In [6]:
import numpy as np
a = np.array ([[-5,0],[4,1]])
b = np.array ([[6,-3],[2,3]])

difference2 = np.subtract (b,a)

print ("\nDifference of b and a")
print (difference2)


Difference of b and a
[[11 -3]
 [-2  2]]
