<a href="https://colab.research.google.com/github/jreevesy/Linear-Algebra-58019/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**REPRESENTING VECTORS**

In [2]:
import numpy as np

A = np.array ([4,3])
B = np.array ([2,-5])

print ('Vector A is', A)
print ('Vector B is', B)

Vector A is [4 3]
Vector B is [ 2 -5]


**DESCRIBING VECTORS IN NumPy**

In [7]:
import numpy as np

### checking shapes
### shapes tells us how many rows and columns are there 

ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])

pool = np.array([ball1,ball2])
pool.shape 
pool.ndim ### dimension

2

In [13]:
u = np.array([[1,2,3],[4,5,6]])
u
u.ndim
u.size ### component in a matrix u

6

**SPACE**

Vector spaces are mathematical objects that abstractly capture the geometry and algebra of linear equations.

Addition of vectors

In [15]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
sum = addend1 + addend2
sum


array([1, 1, 0])

In [16]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
resultant = np.add(addend1, addend2)
resultant

array([1, 1, 0])

**SUBTRACTION OF VECTORS**

In [17]:
#You will subtract the components of addend2 from addend1: addend1-addend2

difference = addend1-addend2
difference

array([-1, -1,  0])

In [19]:
difference2 = np.subtract(addend2,addend1)
difference

array([-1, -1,  0])

**MULTIPLICATION OF VECTORS**

Scaling

In [20]:
A = np.array([1,5,8,9])
S = 5*A
S

array([ 5, 25, 40, 45])

**CROSS PRODUCT**

In [21]:
import numpy as np

#initialize arrays

A = np.array([2,3])
B = np.array ([1,7])

#compute cross product

output = np.cross(A,B)

print (output)

11
